SELECT EXTRACT(MONTH FROM A.START_DATE) AS MONTH
     , A.CAR_ID
     , COUNT(A.CAR_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
        , (SELECT CAR_ID
             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
            WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
              AND START_DATE <= LAST_DAY(TO_DATE('2022-10-01','YYYY-MM-DD'))
            GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) > 4) B
 WHERE A.CAR_ID = B.CAR_ID
   AND A.START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
   AND A.START_DATE <= LAST_DAY(TO_DATE('2022-10-01','YYYY-MM-DD'))
 GROUP BY EXTRACT(MONTH FROM A.START_DATE), A.CAR_ID
 ORDER BY MONTH, CAR_ID DESC