SELECT B.TITLE
     , B.BOARD_ID
     , R.REPLY_ID
     , R.WRITER_ID
     , R.CONTENTS
     , TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B
   , USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
  AND B.CREATED_DATE >= TO_DATE('20221001', 'YYYYMMDD')
  AND B.CREATED_DATE <= LAST_DAY(TO_DATE('20221001', 'YYYYMMDD'))
  --AND TO_CHAR(B.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY R.CREATED_DATE, B.TITLE